# Generated by Django 4.2.30 on 2026-05-30 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchreport',
            name='job_description_snapshot',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='matchreport',
            name='resume_text_snapshot',
            field=models.TextField(blank=True),
        ),
    ]
