# Generated by Django 4.2.30 on 2026-05-30 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobdescription_is_saved_jobdescription_source_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='location',
            field=models.CharField(blank=True, max_length=220),
        ),
    ]
