# Generated by Django 4.2.30 on 2026-05-30 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_jobdescription_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='external_id',
            field=models.CharField(blank=True, max_length=220),
        ),
        migrations.AddConstraint(
            model_name='jobdescription',
            constraint=models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('user', 'source', 'external_id'), name='unique_saved_job_external_id_per_user_source'),
        ),
    ]
