# Generated by Django 4.2.30 on 2026-05-30 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('resumes', '0002_resume_user'),
        ('jobs', '0004_jobdescription_external_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='applied_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='excitement',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='interview_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='recruiter_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='recruiter_name',
            field=models.CharField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='resume_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resumes.resume'),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='salary_text',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='status',
            field=models.CharField(choices=[('saved', 'Saved'), ('preparing', 'Preparing'), ('applied', 'Applied'), ('interview', 'Interview'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='saved', max_length=24),
        ),
        migrations.CreateModel(
            name='SearchAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180)),
                ('title', models.CharField(max_length=180)),
                ('location', models.CharField(blank=True, max_length=180)),
                ('country', models.CharField(default='us', max_length=2)),
                ('workplace', models.CharField(default='any', max_length=24)),
                ('skills', models.CharField(blank=True, max_length=180)),
                ('experience_level', models.CharField(default='any', max_length=24)),
                ('employment_type', models.CharField(default='any', max_length=24)),
                ('salary_min', models.PositiveIntegerField(blank=True, null=True)),
                ('salary_max', models.PositiveIntegerField(blank=True, null=True)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly')], default='weekly', max_length=12)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_alerts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
