# Generated by Django 4.2.30 on 2026-05-31 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_jobdescription_applied_at_jobdescription_excitement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdescription',
            name='cover_letter',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='employment_type',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='experience_level',
            field=models.CharField(blank=True, max_length=24),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='follow_up_email',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='interview_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='personal_pitch',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='star_stories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='tasks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobdescription',
            name='workplace',
            field=models.CharField(blank=True, max_length=24),
        ),
    ]
