# Generated by Django 4.2.30 on 2026-06-02 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_jobdescription_cover_letter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchalert',
            name='excluded_keywords',
            field=models.CharField(blank=True, max_length=240),
        ),
    ]
