# Generated by Codex on 2026-07-07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0007_searchalert_excluded_keywords"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchalert",
            name="source",
            field=models.CharField(default="all", max_length=24),
        ),
    ]
